### ISSUE TITLE
Sets und gets ohne Parameter 1 bzw. Auswahlliste für Sendersuchbegriffe

### ISSUE THREAD

**Issue by supernova1963** [supernova1963/TVSender#12]
Wie kann man die Variablen für die TVSender_gets und TVSender_sets so formatieren, dass für die. Befehle autoCreate bzw. updateAll keine 1 als Parameter eingegeben werden muss, oder z.B. eine Optimierung durch ein Dropdown-Menü mit den aktuellen Sendersuchbegriffen möglich ist?

**Comment by supernova1963** [comment]
Danke CoolTux, 

So etwas findest Du doch ohne Probleme 1. in anderen Modulen, 2. im Developer Guide

AutoCreate:noArg

DropDown
AutoCreate:1,2,3,4,5,6,7

**Comment by supernova1963** [comment]
`my %TVSender_sets = (
"AutoCreate:noArg"     => "AutoCreate",
"Switch2Channel:noArg" => "Switch2Channel",
"UpdateAll:noArg"      => "UpdateAll",
#"NrFavorit"     => "NrFavorit:"
);`
**ergibt durch:**
`sub TVSender_Set($@) {
    my ($hash, @param) = @_;
    return '"set TVProgram" needs at least one argument' if (int(@param) < 2);
    my $name = shift @param;
    my $opt = shift @param;
    my $value = join("", @param);
    if(!$TVSender_gets{$opt}) {
        my @cList = keys %TVSender_gets;
        return "Unknown argument $opt, choose one of " . join(" ", @cList);
    }
...
`

> Unknown argument AutoCreate, choose one of ChannelName UpdateAll AutoCreate Switch2Channel

Ich habe zur Zeit noch keine Ahnung, warum

**Comment by LeonGaultier** [comment]
`sub TVSender_Set($@) {

    my ($hash, $name, $cmd, @args) = @_;
    my ($arg, @params) = @args;
    
    
    my $httpmoddevice = '';
    my $errors = '';
    my $regex = "";
    my $subst = "";

    
    if ($cmd eq 'AutoCreate') {
        if ($arg eq '1') {
          $httpmoddevice = InternalVal($name,'TV_Program_NOW','TV_Program_NOW');
          my $TV_Program_hash = $defs{$httpmoddevice};
          TVSender_Add_HTTPMOD_Device($hash,$httpmoddevice,"Es läuft",1);
          TVSender_Change_HTTPMOD_Device_userattr($hash,$httpmoddevice);
          TVSender_Change_HTTPMOD_Device_stateformat($hash,$httpmoddevice);
          ### TV_Program_NEXT ###
          $httpmoddevice = InternalVal($name,'TV_Program_NEXT','TV_Program_NEXT');
          $TV_Program_hash = $defs{$httpmoddevice};
          TVSender_Add_HTTPMOD_Device($hash,$httpmoddevice,"Anschliessend",2);
          TVSender_Change_HTTPMOD_Device_userattr($hash,$httpmoddevice);
          TVSender_Change_HTTPMOD_Device_stateformat($hash,$httpmoddevice);
          ### TV_Program_PT ###
          $httpmoddevice = InternalVal($name,'TV_Program_PT','TV_Program_PT');
          $TV_Program_hash = $defs{$httpmoddevice};
          TVSender_Add_HTTPMOD_Device($hash,$httpmoddevice,"Zur PrimeTime",3);
          TVSender_Change_HTTPMOD_Device_userattr($hash,$httpmoddevice);
          TVSender_Change_HTTPMOD_Device_stateformat($hash,$httpmoddevice);
          ### TV_Program_PTNEXT ###
          $httpmoddevice = InternalVal($name,'TV_Program_PTNEXT','TV_Program_PTNEXT');
          $TV_Program_hash = $defs{$httpmoddevice};
          TVSender_Add_HTTPMOD_Device($hash,$httpmoddevice,"Danach",4);
          TVSender_Change_HTTPMOD_Device_userattr($hash,$httpmoddevice);
          TVSender_Change_HTTPMOD_Device_stateformat($hash,$httpmoddevice);
        }
    }
    
    elsif ($cmd eq 'Switch2Channel') {
      if ($arg eq "1") {
        #fhem ('"'.AttrVal($name,"SwitchCommand","").'"');
        $cmd = AttrVal($name,"SwitchCommand","");
        $regex = qr/;/p;
        $subst = ';;';
        $cmd = $cmd =~ s/$regex/$subst/rg;
        $errors = '';
        $errors = AnalyzeCommandChain (undef, $cmd);
        if (!defined($errors)) {
          #Log3($name, 3,'Sucsessfully deleted row of stateFormat to '.$httpmoddevice.'!');
        }
        else {
          Log3($name, 5, 'SwitchCommand from '.$name.'cause error: '.$errors.'!');
          Log3($name, 5, $cmd);
        }
      }
    }
    
    elsif ($cmd eq 'UpdateAll') {
      if ($arg eq "1") {
        #fhem ('"'.AttrVal($name,"SwitchCommand","").'"');
        TVSender_Parameter_update ($hash);
      }
      
    } else {
        my $list = "AutoCreate:0,1 Switch2Channel:1 UpdateAll:1";
        return "Unknown argument $cmd, choose one of $list";
    }

    return undef;
}`
